GROUP_DESCRIPTION = APPLICATIONS
MODULES = \
	plc-cape-demo-lib-usage \
	plc-cape-autotest \
	plc-cape-lab \
	plc-cape-freq-response \
	plc-cape-oscilloscope

include $(DEV_SRC_DIR)/+common/make_group.mk
