ADDITIONAL_PLC_LIBS = plc-tools
ADDITIONAL_HEADERS = \
	$(DEV_SRC_DIR)/+common/api/*.h \
	$(DEV_SRC_DIR)/plugins/decoder/api/*.h

TARGET = $(notdir $(CURDIR)).so
include $(DEV_SRC_DIR)/+common/make_object.mk
