GROUP_DESCRIPTION = PLUGINS
MODULES = \
	ui/ui-ncurses ui/ui-console \
	encoder/encoder-wave encoder/encoder-pwm encoder/encoder-ook \
	decoder/decoder-pwm decoder/decoder-ook
	
include $(DEV_SRC_DIR)/+common/make_group.mk
