GROUP_DESCRIPTION = PLUGINS
MODULES = \
	ui/ui-ncurses ui/ui-console \
	encoder/encoder-wave encoder/encoder-pwm encoder/encoder-ook encoder/encoder-wav encoder/encoder-morse \
	decoder/decoder-raw decoder/decoder-pwm decoder/decoder-ook decoder/decoder-morse
	
include $(DEV_SRC_DIR)/+common/make_group.mk
